-- exo 01
--
-- Créez une table profile qui contient les colonnes :
-- - prénom
-- - nom de famille
-- - abonnement newsletter (booléen)
--
-- La relation user 0,1 <-> 1,1 profile est de type « 1 to 1 »
--
-- Créez une table categorie qui contient les colonnes :
-- - nom
-- - description
--
-- La relation categorie 0,n <-> 1,1 post est de type « 1 to many »
--
-- Au besoin, vous devez rajouter les contraintes et indexes
