insert into tag (id, nom) values (1, 'quam pharetra magna');
insert into tag (id, nom) values (2, 'quam');
insert into tag (id, nom) values (3, 'ultrices');
insert into tag (id, nom) values (4, 'cursus vestibulum proin');
insert into tag (id, nom) values (5, 'placerat');
insert into tag (id, nom) values (6, 'cum sociis natoque');
insert into tag (id, nom) values (7, 'sed');
insert into tag (id, nom) values (8, 'tincidunt');
insert into tag (id, nom) values (9, 'mauris sit');
insert into tag (id, nom) values (10, 'libero nam');
insert into tag (id, nom) values (11, 'blandit non interdum');
insert into tag (id, nom) values (12, 'ultrices erat');
insert into tag (id, nom) values (13, 'vestibulum');
insert into tag (id, nom) values (14, 'elit proin interdum');
insert into tag (id, nom) values (15, 'orci pede venenatis');
insert into tag (id, nom) values (16, 'sed accumsan felis');
insert into tag (id, nom) values (17, 'dolor');
insert into tag (id, nom) values (18, 'amet cursus id');
insert into tag (id, nom) values (19, 'elit proin');
insert into tag (id, nom) values (20, 'habitasse platea');
insert into tag (id, nom) values (21, 'semper');
insert into tag (id, nom) values (22, 'ac tellus semper');
insert into tag (id, nom) values (23, 'luctus');
insert into tag (id, nom) values (24, 'suspendisse');
insert into tag (id, nom) values (25, 'turpis');
insert into tag (id, nom) values (26, 'quis turpis');
insert into tag (id, nom) values (27, 'aliquet');
insert into tag (id, nom) values (28, 'vel enim sit');
insert into tag (id, nom) values (29, 'quisque ut erat');
insert into tag (id, nom) values (30, 'nulla ac');
insert into tag (id, nom) values (31, 'dolor vel');
insert into tag (id, nom) values (32, 'blandit ultrices enim');
insert into tag (id, nom) values (33, 'faucibus orci');
insert into tag (id, nom) values (34, 'luctus et ultrices');
insert into tag (id, nom) values (35, 'accumsan odio curabitur');
insert into tag (id, nom) values (36, 'nunc donec quis');
insert into tag (id, nom) values (37, 'luctus foo');
insert into tag (id, nom) values (38, 'diam');
insert into tag (id, nom) values (39, 'in consequat');
insert into tag (id, nom) values (40, 'blandit');
insert into tag (id, nom) values (41, 'a ipsum');
insert into tag (id, nom) values (42, 'vitae nisi');
insert into tag (id, nom) values (43, 'eu');
insert into tag (id, nom) values (44, 'ridiculus mus etiam');
insert into tag (id, nom) values (45, 'lectus aliquam');
insert into tag (id, nom) values (46, 'ut');
insert into tag (id, nom) values (47, 'primis');
insert into tag (id, nom) values (48, 'praesent');
insert into tag (id, nom) values (49, 'porttitor lacus at');
insert into tag (id, nom) values (50, 'ipsum');
